# Generated by Django 3.2.8 on 2021-10-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_text',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
